// <auto-generated />
using System;
using Hexagon.UserManagement.EFCorePostgre;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hexagon.UserManagement.EFCorePostgre.Migrations
{
    [DbContext(typeof(UserManagementDbContext))]
    [Migration("20190228070136_initial3")]
    partial class initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Hexagon.UserManagement.EFCorePostgre.Entity.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Age");

                    b.Property<string>("Gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("RealmId");

                    b.Property<DateTime?>("TokenExpireTime");

                    b.HasKey("Id");

                    b.HasIndex("RealmId");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Hexagon.UserManagement.EFCorePostgre.Entity.Realm", b =>
                {
                    b.Property<int>("RlmId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RealmName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("RlmId");

                    b.ToTable("Realms");
                });

            modelBuilder.Entity("Hexagon.UserManagement.EFCorePostgre.Entity.RealmSolution", b =>
                {
                    b.Property<int>("RlmId");

                    b.Property<int>("SlnId");

                    b.HasKey("RlmId", "SlnId");

                    b.HasIndex("SlnId");

                    b.ToTable("RealmSolution");
                });

            modelBuilder.Entity("Hexagon.UserManagement.EFCorePostgre.Entity.Solution", b =>
                {
                    b.Property<int>("SlnId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SolutionName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("SlnId");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("Hexagon.UserManagement.EFCorePostgre.Entity.AdminUser", b =>
                {
                    b.HasOne("Hexagon.UserManagement.EFCorePostgre.Entity.Realm", "Realm")
                        .WithMany("Users")
                        .HasForeignKey("RealmId");
                });

            modelBuilder.Entity("Hexagon.UserManagement.EFCorePostgre.Entity.RealmSolution", b =>
                {
                    b.HasOne("Hexagon.UserManagement.EFCorePostgre.Entity.Realm", "Realm")
                        .WithMany("RealmSolutions")
                        .HasForeignKey("RlmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hexagon.UserManagement.EFCorePostgre.Entity.Solution", "Solution")
                        .WithMany("RealmSolutions")
                        .HasForeignKey("SlnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
